---
- name: Create Virtual Machine Snapshot
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vcenter_host: "{{ lookup('env', 'VMWARE_HOST') }}"
    vcenter_user: "{{ lookup('env', 'VMWARE_USER') }}"
    vcenter_pass: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    vcenter_certs: "{{ lookup('env', 'VMWARE_VALIDATE_CERTS') }}"

  tasks:
    - name: Validate required variables
      assert:
        that:
          - vm_name is defined
          - vm_datacenter is defined
          - snapshot_name is defined
          - snapshot_name | length > 0
        fail_msg: "Required variables missing: vm_name, vm_datacenter, and snapshot_name must be defined"
        success_msg: "All required variables are defined"

    - name: Display snapshot creation parameters
      debug:
        msg:
          - "VM Name: {{ vm_name }}"
          - "Datacenter: {{ vm_datacenter }}"
          - "Snapshot Name: {{ snapshot_name }}"
          - "VM Subfolder: {{ vm_subfolder | default('(none)') }}"

    - name: Set folder path
      set_fact:
        vm_folder_path: >-
          {%- if vm_subfolder is defined and vm_subfolder | length > 0 -%}
            /{{ vm_datacenter }}/vm/{{ vm_subfolder }}
          {%- else -%}
            /{{ vm_datacenter }}/vm
          {%- endif -%}

    - name: Display folder path
      debug:
        msg: "Using folder path: {{ vm_folder_path }}"

    - name: Create VM snapshot
      vmware.vmware.vm_snapshot:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: "{{ vcenter_certs | default(false, true) }}"
        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder_path }}"
        name: "{{ vm_name }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
        description: "Snapshot created by Ansible on {{ ansible_date_time.iso8601 }}"
        memory: false
        quiesce: false
      delegate_to: localhost
      register: snapshot_result

    - name: Display snapshot creation result
      debug:
        var: snapshot_result

    - name: Verify snapshot was created
      assert:
        that:
          - snapshot_result is succeeded
          - snapshot_result.changed == true
        fail_msg: "Snapshot creation may have failed - task did not report changes"
        success_msg: "Snapshot task completed with changes"

    - name: List VM snapshots to verify creation
      vmware.vmware.vm_snapshot:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: "{{ vcenter_certs | default(false, true) }}"
        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder_path }}"
        name: "{{ vm_name }}"
        state: list
      delegate_to: localhost
      register: snapshot_list

    - name: Display all snapshots
      debug:
        var: snapshot_list

    - name: Verify snapshot exists in list
      assert:
        that:
          - snapshot_list.snapshots is defined
          - snapshot_name in (snapshot_list.snapshots | map(attribute='name') | list)
        fail_msg: "Snapshot '{{ snapshot_name }}' was not found in the snapshot list"
        success_msg: "Snapshot '{{ snapshot_name }}' successfully verified in vCenter"

