---
- name: Create Virtual Machine Snapshot
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Create VM snapshot
      vmware.vmware.vm_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs | default(false) }}"
        datacenter: "{{ vm_datacenter }}"
        name: "{{ vm_name }}"
        state: present
        snapshot_name: "{{ snapshot_name }}"
      delegate_to: localhost

