---
- name: Debug become behavior
  hosts: all
  gather_facts: false

  tasks:
    - name: Show effective user
      ansible.builtin.command: whoami
      register: whoami_out
      changed_when: false

    - ansible.builtin.debug:
        msg: "whoami => {{ whoami_out.stdout }}"

    - name: Show ansible become vars
      ansible.builtin.debug:
        var: ansible_become
    - ansible.builtin.debug:
        var: ansible_become_method
    - ansible.builtin.debug:
        var: ansible_become_user

    - name: Test non-interactive sudo (sudo -n true)
      ansible.builtin.command: sudo -n true
      register: sudo_test
      failed_when: false
      changed_when: false

    - ansible.builtin.debug:
        msg: "sudo -n rc={{ sudo_test.rc }} stderr='{{ sudo_test.stderr }}'"

    - name: Exit
      ansible.builtin.debug:
        msg: "End of debug play"
