---
- name: Configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    # This file contains the controller_username and controller_password
    # and should be encrypted with Ansible Vault.
    - controller_vars.yml

  # ========================================================================
  # PRE-TASKS: Authenticate and create a temporary token for this run
  # ========================================================================
  pre_tasks:
    - name: Verify controller connection variables are defined
      debug:
        msg: |
          Variable check:
          - controller_host: {{ 'DEFINED' if controller_host is defined else 'MISSING' }} ({{ controller_host | default('NOT SET') }})
          - controller_username: {{ 'DEFINED' if controller_username is defined else 'MISSING' }} ({{ controller_username | default('NOT SET') }})
          - controller_password: {{ 'DEFINED' if controller_password is defined else 'MISSING' }} (length: {{ controller_password | length | default(0) }})
          - controller_validate_certs: {{ 'DEFINED' if controller_validate_certs is defined else 'MISSING' }} ({{ controller_validate_certs | default('NOT SET') }})
      failed_when: controller_host is not defined or controller_username is not defined or controller_password is not defined

    - name: Test controller login endpoint
      uri:
        url: "{{ controller_host }}/api/login/"
        method: POST
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        force_basic_auth: true
        status_code: [200, 401, 403]
        body_format: json
      register: login_test
      ignore_errors: true

    - name: Display login test result
      debug:
        msg: |
          Login test result:
          Status: {{ login_test.status | default('Unknown') }}
          {% if login_test.status == 200 %}
          Successfully authenticated to controller!
          {% elif login_test.status == 401 %}
          Authentication failed (401) - please verify username and password are correct
          {% elif login_test.status == 403 %}
          Authentication failed (403) - account may be disabled or lacks permissions
          {% else %}
          Login test failed: {{ login_test.msg | default('Unknown error') }}
          {% endif %}
      when: login_test is defined

    - name: Generate a temporary OAuth2 token for this playbook run
      ansible.controller.token:
        description: "Temporary token for CaC playbook run on {{ ansible_date_time.iso8601 }}"
        scope: "write"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
      register: generated_token
      no_log: true # Prevents credentials from appearing in logs

    - name: Display token generation error if failed
      debug:
        msg: |
          Token generation failed!
          Error: {{ generated_token.msg | default('Unknown error') }}
          Full error details: {{ generated_token | to_nice_json }}
      when: generated_token is failed

  # ========================================================================
  # MAIN TASKS: Include roles to deploy AAP resources
  # ========================================================================
  roles:
    - role: deploy_inventories

  # ========================================================================
  # POST-TASKS: Clean up by deleting the temporary token
  # ========================================================================
  post_tasks:
    - name: Delete the temporary OAuth2 token
      ansible.controller.token:
        id: "{{ generated_token.ansible_facts.controller_token.id }}"
        state: absent
        controller_host: "{{ controller_host }}"
        # Authenticate the deletion request with the token we are about to delete
        controller_oauthtoken: "{{ generated_token.ansible_facts.controller_token.token }}"
        validate_certs: "{{ controller_validate_certs }}"
      no_log: true # Prevents token from appearing in logs
