---
- name: Configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # This file contains the controller_username and controller_password
    # and should be encrypted with Ansible Vault.
    - controller_vars.yml

  # ========================================================================
  # PRE-TASKS: Authenticate and create a temporary token for this run
  # ========================================================================
  pre_tasks:
    - name: Generate a temporary OAuth2 token for this playbook run
      ansible.controller.token:
        description: "Temporary token for CaC playbook run on {{ ansible_date_time.iso8601 }}"
        scope: "write"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
      register: generated_token
      no_log: true # Prevents credentials from appearing in logs

  # ========================================================================
  # MAIN TASKS: Include roles to deploy AAP resources
  # ========================================================================
  roles:
    - role: deploy_inventories

  # ========================================================================
  # POST-TASKS: Clean up by deleting the temporary token
  # ========================================================================
  post_tasks:
    - name: Delete the temporary OAuth2 token
      ansible.controller.token:
        id: "{{ generated_token.token.id }}"
        state: absent
        controller_host: "{{ controller_host }}"
        # Authenticate the deletion request with the token we are about to delete
        controller_oauthtoken: "{{ generated_token.token.token }}"
        validate_certs: "{{ controller_validate_certs }}"
      no_log: true # Prevents token from appearing in logs
