---
- name: Configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # This file contains the controller_username and controller_password
    # and should be encrypted with Ansible Vault.
    - controller_vars.yml

  # ========================================================================
  # PRE-TASKS: Load exported inventories and authenticate
  # ========================================================================
  pre_tasks:
    - name: Find exported inventory files
      find:
        paths: "{{ playbook_dir }}/files"
        patterns: "export-results-*.yaml"
        file_type: file
      register: exported_files

    - name: Load exported inventory data from files
      set_fact:
        exported_data: "{{ exported_data | default([]) + [(lookup('file', item.path) | from_yaml)] }}"
      loop: "{{ exported_files.files }}"
      when: exported_files.matched > 0

    - name: Transform exported inventories format (flatten organization.name to organization)
      set_fact:
        controller_inventories: "{{ controller_inventories | default([]) + [{
          'name': inv.name,
          'organization': inv.organization.name,
          'description': inv.description | default('') | string
        }] }}"
      loop: "{{ exported_data | map(attribute='inventory') | flatten | default([]) }}"
      loop_control:
        label: "{{ inv.name }}"
      vars:
        inv: "{{ item }}"
      when: exported_files.matched > 0

    - name: Load manual inventory definitions from role vars if no exported files found
      include_vars:
        file: "{{ playbook_dir }}/roles/deploy_inventories/vars/main.yml"
        name: role_vars
      when: exported_files.matched == 0

    - name: Set controller_inventories from role vars when no files exist
      set_fact:
        controller_inventories: "{{ role_vars.controller_inventories | default([]) }}"
      when: exported_files.matched == 0

    - name: Display inventories to be deployed
      debug:
        msg: |
          Source: {{ 'Exported files' if exported_files.matched > 0 else 'Manual vars (roles/deploy_inventories/vars/main.yml)' }}
          Will deploy {{ controller_inventories | length }} inventories: {{ controller_inventories | map(attribute='name') | list }}
      when: controller_inventories is defined

    - name: Generate a temporary OAuth2 token for this playbook run
      ansible.controller.token:
        description: "Temporary token for CaC playbook run on {{ ansible_date_time.iso8601 }}"
        scope: "write"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
      register: generated_token
      no_log: true # Prevents credentials from appearing in logs

  # ========================================================================
  # MAIN TASKS: Include roles to deploy AAP resources
  # ========================================================================
  roles:
    - role: deploy_inventories

  # ========================================================================
  # POST-TASKS: Clean up by deleting the temporary token
  # ========================================================================
  post_tasks:
    - name: Delete the temporary OAuth2 token
      ansible.controller.token:
        id: "{{ generated_token.token.id }}"
        state: absent
        controller_host: "{{ controller_host }}"
        # Authenticate the deletion request with the token we are about to delete
        controller_oauthtoken: "{{ generated_token.token.token }}"
        validate_certs: "{{ controller_validate_certs }}"
      no_log: true # Prevents token from appearing in logs

